apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp01
  template:
    metadata:
      labels:
        app: myapp01
    spec:
      containers:
      - name: myapp01
        image: nginx:1.19.10
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

