apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh"]
    args: ["-c","Sleep 10000"]
    env:
      - name: log_level
        valueFrom:
          configMapKeyRef:
            name: log-config
            key: log.level